### ISSUE TITLE
Nuget listed as .NET Nuget instead of VL Nuget

### ISSUE THREAD

**Issue by jhnnslmk** [cnisidis/VL.SharedMemory#1]
![image](https://user-images.githubusercontent.com/1488726/91998727-e049ae80-ed3b-11ea-8a25-dc6e97f6e3da.png)

**Comment by cnisidis** [comment]
this is correct as far as i know, VL Nugets are in-house (vvvv gamma) nugets, other contributions are marjed as net nugets, I have no clue if it is possible or if I can mention it as  a VL nuget directly. Thanks for the indication!

**Comment by cnisidis** [comment]
I tried to resolve this but without any success, I have no idea how to do it. Although another problem I encountered is that after installing the nuget pack I still cant access it from the node browser. I suppose that this one has to do with forwarding but I might be wrong. i ll address it to the forum and get a certain answer.

**Comment by jhnnslmk** [comment]
Alright.
.NET nugets are dlls, VL nugets are .vl files.
You can check Elementa for example, which is also listed in VL Nugets.

Maybe that's the same reason why it's not showing up in the node browser.

**Comment by cnisidis** [comment]
ok, sounds reasonable, but I have only a VL file, no dll's or other .NET related stuff. Thanks for the info!

**Comment by tebjan** [comment]
The main vl doc must be in the root folder of the package and have the same name as the package. e.g. `VL.SharedMemory.vl`

**Comment by cnisidis** [comment]
oh right, I see thanks  lot @tebjan !

**Comment by cnisidis** [comment]
check v 0.0.3
