### ISSUE TITLE
Dependencies missing from Nuget file

### ISSUE THREAD

**Issue by jhnnslmk** [cnisidis/VL.SharedMemory#2]
I didn't find it in the nodebrowser after installing the nuget so I checked the .vl file - the dependencies should be listed so they are getting grabbed when installing the nuget I guess:
![image](https://user-images.githubusercontent.com/1488726/91999118-54845200-ed3c-11ea-9ba8-ca797454ea05.png)

**Comment by cnisidis** [comment]
hm, I should probably add them as dependencies or forward them. It is easy to fix atm on your side if you right click and install them. I ll mention them in the nuspec file asap. thanks!

**Comment by jhnnslmk** [comment]
Hey,
yes of course, it can be fixed and works when I clone the repository.
Just thought I’d let you know about the broken nuget :)

Thanks

**Comment by cnisidis** [comment]
Sure, well done, it will be fixed on the next release!

**Comment by cnisidis** [comment]
Dependencies added (v0.0.2)
