### ISSUE TITLE
Introduce correct namespace

### ISSUE THREAD

**Issue by jhnnslmk** [cnisidis/VL.SharedMemory#3]
Maybe IO or System? Not sure ...
![image](https://user-images.githubusercontent.com/1488726/91999254-7a115b80-ed3c-11ea-9e0d-e467d429bcc1.png)

**Comment by cnisidis** [comment]
you are right, better to have its own namespace! Again, this will be fixed as soon as I am back on my workstation! Thanks again!

**Comment by cnisidis** [comment]
namespace changed to SharedMemory
